#include "ChessField.h"


int ChessField::field2Index(ChessField::CHESS_FILEDS _field)
{
	return static_cast<int>(_field);
}


ChessField::CHESS_FILEDS ChessField::get_field_from_board_index(int _board_index)
{
	
	const CHESS_FILEDS LUT[96] = { 
		//-------------- ROW 0 ---------------------------- //
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_WHITE_1,
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_WHITE_2,
		
		CHESS_FILEDS::CHESS_FIELD_A8,
		CHESS_FILEDS::CHESS_FIELD_B8,
		CHESS_FILEDS::CHESS_FIELD_C8,
		CHESS_FILEDS::CHESS_FIELD_D8,
		CHESS_FILEDS::CHESS_FIELD_E8,
		CHESS_FILEDS::CHESS_FIELD_F8,
		CHESS_FILEDS::CHESS_FIELD_G8,
		CHESS_FILEDS::CHESS_FIELD_H8,
			
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_BLACK_1,
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_BLACK_2,
		
		
		
		//-------------- ROW 1 ---------------------------- //
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_WHITE_3,
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_WHITE_4,
		
		CHESS_FILEDS::CHESS_FIELD_A7,
		CHESS_FILEDS::CHESS_FIELD_B7,
		CHESS_FILEDS::CHESS_FIELD_C7,
		CHESS_FILEDS::CHESS_FIELD_D7,
		CHESS_FILEDS::CHESS_FIELD_E7,
		CHESS_FILEDS::CHESS_FIELD_F7,
		CHESS_FILEDS::CHESS_FIELD_G7,
		CHESS_FILEDS::CHESS_FIELD_H7,
			
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_BLACK_3,
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_BLACK_4,
		
		
		
		//-------------- ROW 2 ---------------------------- //
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_WHITE_5,
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_WHITE_6,
		
		CHESS_FILEDS::CHESS_FIELD_A6,
		CHESS_FILEDS::CHESS_FIELD_B6,
		CHESS_FILEDS::CHESS_FIELD_C6,
		CHESS_FILEDS::CHESS_FIELD_D6,
		CHESS_FILEDS::CHESS_FIELD_E6,
		CHESS_FILEDS::CHESS_FIELD_F6,
		CHESS_FILEDS::CHESS_FIELD_G6,
		CHESS_FILEDS::CHESS_FIELD_H6,
			
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_BLACK_5,
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_BLACK_6,
		
		
		//-------------- ROW 3 ---------------------------- //
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_WHITE_7,
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_WHITE_8,
		
		CHESS_FILEDS::CHESS_FIELD_A5,
		CHESS_FILEDS::CHESS_FIELD_B5,
		CHESS_FILEDS::CHESS_FIELD_C5,
		CHESS_FILEDS::CHESS_FIELD_D5,
		CHESS_FILEDS::CHESS_FIELD_E5,
		CHESS_FILEDS::CHESS_FIELD_F5,
		CHESS_FILEDS::CHESS_FIELD_G5,
		CHESS_FILEDS::CHESS_FIELD_H5,
			
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_BLACK_7,
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_BLACK_8,
		
		//-------------- ROW 4 ---------------------------- //
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_WHITE_9,
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_WHITE_10,
		
		CHESS_FILEDS::CHESS_FIELD_A4,
		CHESS_FILEDS::CHESS_FIELD_B4,
		CHESS_FILEDS::CHESS_FIELD_C4,
		CHESS_FILEDS::CHESS_FIELD_D4,
		CHESS_FILEDS::CHESS_FIELD_E4,
		CHESS_FILEDS::CHESS_FIELD_F4,
		CHESS_FILEDS::CHESS_FIELD_G4,
		CHESS_FILEDS::CHESS_FIELD_H4,
			
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_BLACK_9,
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_BLACK_10,
		
		
		
		//-------------- ROW 5 ---------------------------- //
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_WHITE_11,
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_WHITE_12,
		
		CHESS_FILEDS::CHESS_FIELD_A3,
		CHESS_FILEDS::CHESS_FIELD_B3,
		CHESS_FILEDS::CHESS_FIELD_C3,
		CHESS_FILEDS::CHESS_FIELD_D3,
		CHESS_FILEDS::CHESS_FIELD_E3,
		CHESS_FILEDS::CHESS_FIELD_F3,
		CHESS_FILEDS::CHESS_FIELD_G3,
		CHESS_FILEDS::CHESS_FIELD_H3,
			
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_BLACK_11,
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_BLACK_12,
		
		
		//-------------- ROW 6 ---------------------------- //
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_WHITE_13,
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_WHITE_14,
		
		CHESS_FILEDS::CHESS_FIELD_A2,
		CHESS_FILEDS::CHESS_FIELD_B2,
		CHESS_FILEDS::CHESS_FIELD_C2,
		CHESS_FILEDS::CHESS_FIELD_D2,
		CHESS_FILEDS::CHESS_FIELD_E2,
		CHESS_FILEDS::CHESS_FIELD_F2,
		CHESS_FILEDS::CHESS_FIELD_G2,
		CHESS_FILEDS::CHESS_FIELD_H2,
			
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_BLACK_13,
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_BLACK_14,
		
		
		//-------------- ROW 7 ---------------------------- //
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_WHITE_15,
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_WHITE_16,
		
		CHESS_FILEDS::CHESS_FIELD_A1,
		CHESS_FILEDS::CHESS_FIELD_B1,
		CHESS_FILEDS::CHESS_FIELD_C1,
		CHESS_FILEDS::CHESS_FIELD_D1,
		CHESS_FILEDS::CHESS_FIELD_E1,
		CHESS_FILEDS::CHESS_FIELD_F1,
		CHESS_FILEDS::CHESS_FIELD_G1,
		CHESS_FILEDS::CHESS_FIELD_H1,
			
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_BLACK_15,
		CHESS_FILEDS::CHESS_FIELD_PARK_POSTION_BLACK_16,
	};
	
	
	return LUT[_board_index];
}